language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2

before_install:
  - mvn -v
install:
  - mvn dependency:go-offline -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn integration-test -Dmaven.javadoc.skip=true -B -V