language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - /tmp/.hirezsessions
  - ~/.m2/repository

before_install:
  - .deploy/pre-deploy.sh
install:
  - mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B
  - mvn dependency:go-offline -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B
script:
  - mvn test -P !build-extras -B
deploy:
  provider: script
  script: .deploy/deploy.sh
  skip_cleanup: true
  on:
    tags: true
