language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - ~/.m2/repository

install:
  - mvn install -Dmaven.javadoc.skip=true  -P !build-extras -B
  - mvn dependency:go-offline -Dmaven.javadoc.skip=true -P !build-extras -B
script:
  - mvn test -DskipTest=false -Dmaven.javadoc.skip=true -P !build-extras -B
  - mvn cobertura:cobertura -Dmaven.javadoc.skip=true -P !build-extras -B
after_success:
  - bash <(curl -s https://codecov.io/bash)
